import type { Metadata } from "next";
import "../styles/global.css";
import Header from "../components/layout/Header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-poppins antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
